{
 "title": "Crud-ingress",
 "description": "Crud-ingress dashboard",
 "time": { "from": "2024-01-03T15:28:05.367Z", "to": "2024-01-03T15:53:11.750Z" },
 "panels": [
  {
   "title": "GET crud latency",
   "type": "timeseries",
   "description": "GET crud latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"crud-ingress\", method=\"GET\"}[1m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"crud-ingress\", method=\"GET\"}[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"crud-ingress\", method=\"GET\"}[1m])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "POST (CREATE) crud latency",
   "type": "timeseries",
   "description": "POST (CREATE user) crud latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"crud-ingress\", method=\"POST\"}[1m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"crud-ingress\", method=\"POST\"}[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"crud-ingress\", method=\"GET\"}[1m])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "GET performance",
   "type": "stat",
   "description": "GET user performance",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=\"crud-ingress\", method=\"GET\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET error rate",
   "type": "stat",
   "description": "GET error rate",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(rate(nginx_ingress_controller_requests{ingress=\"crud-ingress\", method=\"GET\", status=~\"4..|5..\"}[1m]))/clamp_min(sum(rate(nginx_ingress_controller_requests{ingress=\"crud-ingress\", method=\"GET\"}[1m])),1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST (CREATE) performance",
   "type": "stat",
   "description": "CREATE user performance",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=\"crud-ingress\", method=\"POST\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST(CREATE) error rate",
   "type": "stat",
   "description": "POST(CREATE) error rate",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(rate(nginx_ingress_controller_requests{ingress=\"crud-ingress\", method=\"POST\", status=~\"4..|5..\"}[1m]))/clamp_min(sum(rate(nginx_ingress_controller_requests{ingress=\"crud-ingress\", method=\"POST\"}[1m])),1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT (UPDATE) crud latency",
   "type": "timeseries",
   "description": "PUT (UPDATE user) crud latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"crud-ingress\", method=\"PUT\"}[1m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"crud-ingress\", method=\"PUT\"}[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"crud-ingress\", method=\"PUT\"}[1m])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "PUT (UPDATE) crud latency",
   "type": "timeseries",
   "description": "PUT (UPDATE user) crud latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"crud-ingress\", method=\"PUT\"}[1m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"crud-ingress\", method=\"PUT\"}[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_response_duration_seconds_bucket{ingress=\"crud-ingress\", method=\"PUT\"}[1m])))",
     "legendFormat": "0.99"
    }
   ]
  },
  {
   "title": "PUT(UPDATE) performance",
   "type": "stat",
   "description": "UPDATE user performance",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=\"crud-ingress\", method=\"PUT\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PUT(UPDATE) error rate",
   "type": "stat",
   "description": "PUT(UPDATE) error rate",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(rate(nginx_ingress_controller_requests{ingress=\"crud-ingress\", method=\"PUT\", status=~\"4..|5..\"}[1m]))/clamp_min(sum(rate(nginx_ingress_controller_requests{ingress=\"crud-ingress\", method=\"PUT\"}[1m])),1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELETE performance",
   "type": "stat",
   "description": "DELETE user performance",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=\"crud-ingress\", method=\"DELETE\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELETE error rate",
   "type": "stat",
   "description": "DELETE error rate",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(rate(nginx_ingress_controller_requests{ingress=\"crud-ingress\", method=\"DELETE\", status=~\"4..|5..\"}[1m]))/clamp_min(sum(rate(nginx_ingress_controller_requests{ingress=\"crud-ingress\", method=\"DELETE\"}[1m])),1)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}