{
 "title": "Crud service metrics",
 "description": "Метрики сервиса crud-service",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "GET Latency",
   "type": "timeseries",
   "description": "GET user latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by(quantile) (getUser_duration_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CREATE Latency",
   "type": "timeseries",
   "description": "CREATE User performance",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max by(quantile) (createUser_duration_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET performance",
   "type": "stat",
   "description": "Get user performance rate",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(getUser_duration_seconds_count[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET Error rate",
   "type": "stat",
   "description": "4**/5** erorrs percentage from total number of getUser requests",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(rate(getUser_errorCounter_total[30s]))/clamp_min(sum(rate(getUser_duration_seconds_count[30s])),1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CREATE performance",
   "type": "stat",
   "description": "Create user performance",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(createUser_duration_seconds_count[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CREATE Error rate",
   "type": "stat",
   "description": "4**/5** erorrs percentage from total number of createUser requests",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(rate(createUser_errorCounter_total[30s]))/clamp_min(sum(rate(createUser_duration_seconds_count[30s])),1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPDATE Latency",
   "type": "timeseries",
   "description": "Update User Latency",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "max by(quantile) (updateUser_duration_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELETE latency",
   "type": "timeseries",
   "description": "Delete User Latency",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "max by(quantile) (deleteUser_duration_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPDATE performance",
   "type": "stat",
   "description": "Update user performance",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(updateUser_duration_seconds_count[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPDATE Error rate",
   "type": "stat",
   "description": "4**/5** erorrs percentage from total number of update requests",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(rate(updateUser_errorCounter_total[30s]))/clamp_min(sum(rate(updateUser_duration_seconds_count[30s])),1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELETE performance",
   "type": "stat",
   "description": "Delete user performance",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(deleteUser_duration_seconds_count[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELETE Error rate",
   "type": "stat",
   "description": "4**/5** erorrs percentage from total number of deleteUser requests",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*sum(rate(deleteUser_errorCounter_total[30s]))/clamp_min(sum(rate(deleteUser_duration_seconds_count[30s])),1)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}